# Generated by Django 5.0.1 on 2024-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idP', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NameP', models.CharField(max_length=100)),
                ('Dob', models.DateTimeField(auto_now=True, verbose_name='')),
                ('Sex', models.BooleanField(verbose_name='')),
                ('Phone_Number', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=1000)),
            ],
        ),
    ]
