# Generated by Django 5.0.1 on 2024-03-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Sex',
        ),
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Dob',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone_Number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
